FROM node:20 AS base
WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

FROM node:20 as release
WORKDIR /app

ARG APP_PORT=3000

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg exiftool

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next
COPY --from=base /app/src ./src
COPY --from=base /app .
COPY . .

EXPOSE ${APP_PORT}

CMD ["npm", "run", "dev"]
