FROM node:20 AS base
WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine3.19 as release
WORKDIR /app

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg exiftool

ARG APP_PORT=3000

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next
COPY . .

EXPOSE ${APP_PORT}

CMD ["npm", "run", "start"]
